# On teste automatiquement
# le code ANTLR4.

name: CI
on: push
jobs:
  test-code:
    name: Teste Calculette.g4
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2

    steps:

      - name: Test d'expressions
        run: source tools/ci_script.sh
        shell: bash
